### ISSUE TITLE
Some server send back incorrect Location header because of this line 

### ISSUE THREAD

**Issue by ojomio** [gwik/geventhttpclient#108]
https://github.com/gwik/geventhttpclient/blob/504e0bee4b13afb4aea342458c80433723c61572/src/geventhttpclient/client.py#L156

The conversation goes like this 
```
CONNECT ru.gecid.com:80 HTTP/1.1

HTTP/1.1 200 Connection established

GET http://ru.gecid.com/power/ HTTP/1.1
user-agent: python/gevent-http-client-1.3.1dev
host: ru.gecid.com

HTTP/1.1 301 Moved Permanently
Date: Thu, 04 Oct 2018 10:35:38 GMT
Server: Apache/2.4.25 (FreeBSD) OpenSSL/1.0.2j-freebsd PHP/7.1.5
X-Powered-By: PHP/7.1.5
Location: https://ru.gecid.comhttp://ru.gecid.com/power/
Last-Modified: Wed, 01 Apr 2015 08:33:08 GMT
Expires: Thu, 04 Oct 2018 10:35:38 GMT
Cache-Control: max-age=2592000
Pragma: no-cache
Set-Cookie: gc=61d53ec098ee765e71db6fe40c70299f; path=/; HttpOnly
Set-Cookie: gch=a1e037373160146254c2123b337b7371; path=/
X-XSS-Protection: 1; mode=block
Content-Language: ru
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8

```

with the `Location: https://ru.gecid.comhttp://ru.gecid.com/power/` line being definitely wrong

If I comment the abovementioned line I get the following
```
CONNECT ru.gecid.com:80 HTTP/1.1

HTTP/1.1 200 Connection established

GET /power/ HTTP/1.1
user-agent: python/gevent-http-client-1.3.1dev
host: ru.gecid.com

HTTP/1.1 301 Moved Permanently
Date: Thu, 04 Oct 2018 10:38:56 GMT
Server: Apache/2.4.25 (FreeBSD) OpenSSL/1.0.2j-freebsd PHP/7.1.5
X-Powered-By: PHP/7.1.5
Location: https://ru.gecid.com/power/
Last-Modified: Wed, 01 Apr 2015 08:33:08 GMT
Expires: Thu, 04 Oct 2018 10:38:56 GMT
Cache-Control: max-age=2592000
Pragma: no-cache
Set-Cookie: gc=445b2462b6249383cc29b2edada25d99; path=/; HttpOnly
Set-Cookie: gch=1c3845dacb7d7360c651ba8affabb3ad; path=/
X-XSS-Protection: 1; mode=block
Content-Language: ru
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8

205b
```

Can somebody explain why this line exists?

**Comment by ml31415** [comment]
The line you mentioned should only be reached, when you use a proxy connection. Did you unintentionally set a proxy host? We recently also had some changes with the proxy code, not sure if that might be the cause for this issue.

**Comment by ojomio** [comment]
I deliberately used proxy, as you can see from connect verb in the log. This part of code dates back to 2011 or kinda and should not be connected with any fresh changes

**Comment by ml31415** [comment]
Our test coverage for proxy use is literally zero so far. You're probably the first to give the proxy usage a thorough testing, I'm afraid. :( Not even a stub for `test_proxy`... shame on us. The project right now is not actively maintained by anyone. Pls consider this when you use it for your company projects. Though, help with patches and maintenance always welcome of course!

**Comment by cyberw** [comment]
Closed due to inactivity.
