### ISSUE TITLE
Mark and skip tests that require online enviroment

### ISSUE THREAD

**Issue by scarabeusiv** [gwik/geventhttpclient#112]
When distributions execute testsuite we often have buildbots that can't reach out to the internet for security reasons.

Currently there are few tests that we manualy skip but it should be pretty easy to skip them instead if offline enviroment is detected:
*  test_client_simple                                                          
*  test_client_without_leading_slash                                           
*  test_request_with_headers                                                   
*  test_response_context_manager                                               
*  test_client_ssl                                                             
*  test_ssl_fail_invalid_certificate                                           
*  test_multi_queries_greenlet_safe

**Comment by ml31415** [comment]
Yeah, that sounds great. Do you want to file a PR with the markers in place?

**Comment by scarabeusiv** [comment]
Oky I will create it, Tomorrow as I would like to test it too prior I send it to you (otherwise it is just adding 7 lines :)).
