### ISSUE TITLE
Release request :)

### ISSUE THREAD

**Issue by laurentL** [gwik/geventhttpclient#114]
Hi,
Could you release a new version?
The last is from 2016..
Thanks

**Comment by heyman** [comment]
The current master version is available at the pypi package geventhttpclient-wheels (https://pypi.org/project/geventhttpclient-wheels/). 

I'd be happy to setup automatic building and uploading to PyPI (when a tag is pushed) for this repo if someone would give me access to the repo and the geventhttpclient package on PyPI. (My PyPI username is heyman). 

See #93 and #94.

**Comment by ml31415** [comment]
@gwik yeah, more people with access to the pypi repository would be nice indeed. +1 for giving access to @heyman

**Comment by cyberw** [comment]
Fixed by @gwik today!
