### ISSUE TITLE
geventhttpclient bug when used with Locust

### ISSUE THREAD

**Issue by ecc256** [gwik/geventhttpclient#117]
I've reported geventhttpclient bug [here](https://github.com/locustio/locust/issues/1130), could somebody take a look, please?

**Comment by ml31415** [comment]
Guessing from the trace that you posted, I suppose you're not using the latest version / master of geventhttpclient. As far as I remember that bug was already fixed a while ago.

**Comment by ecc256** [comment]
Michael,
**Thanks for the tip!**
Look like the root issue is in gevent and it is fixed already.
So following works for Python 3.8
`pip install git+git://github.com/gevent/gevent@master`
`pip install git+git://github.com/gwik/geventhttpclient@master`

But not `geventhttpclient` alone
`pip install git+git://github.com/gwik/geventhttpclient@master`

Adding 
`pip install locust`
to the former works too!
WooHoo!!!

**Comment by ml31415** [comment]
@gwik is unfortunately still the only one who can update and push to the pypi repository.

**Comment by SidharthLala1** [comment]
PS D:\Docker Sample Projects\cmder> pip install locust
Collecting locust
  Downloading locust-0.0.tar.gz (833 bytes)
Collecting locustio
  Using cached locustio-0.14.5-py3-none-any.whl (262 kB)
Requirement already satisfied: msgpack>=0.6.2 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (1.0.0)
Requirement already satisfied: psutil>=5.6.7 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (5.7.0)
Requirement already satisfied: flask>=0.10.1 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (1.1.2)
Requirement already satisfied: requests>=2.9.1 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (2.23.0)
Requirement already satisfied: ConfigArgParse>=1.0 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (1.2)
Requirement already satisfied: gevent==1.5a3 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (1.5a3)
Collecting geventhttpclient-wheels==1.3.1.dev2
  Using cached geventhttpclient-wheels-1.3.1.dev2.tar.gz (54 kB)
Requirement already satisfied: pyzmq>=16.0.2 in d:\softwares\python\python38-32\lib\site-packages (from locustio->locust) (19.0.0)
Requirement already satisfied: click>=5.1 in d:\softwares\python\python38-32\lib\site-packages (from flask>=0.10.1->locustio->locust) (7.1.1)
Requirement already satisfied: Werkzeug>=0.15 in d:\softwares\python\python38-32\lib\site-packages (from flask>=0.10.1->locustio->locust) (1.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in d:\softwares\python\python38-32\lib\site-packages (from flask>=0.10.1->locustio->locust) (2.11.1)
Requirement already satisfied: itsdangerous>=0.24 in d:\softwares\python\python38-32\lib\site-packages (from flask>=0.10.1->locustio->locust) (1.1.0)
Requirement already satisfied: chardet<4,>=3.0.2 in d:\softwares\python\python38-32\lib\site-packages (from requests>=2.9.1->locustio->locust) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\softwares\python\python38-32\lib\site-packages (from requests>=2.9.1->locustio->locust) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in d:\softwares\python\python38-32\lib\site-packages (from requests>=2.9.1->locustio->locust) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\softwares\python\python38-32\lib\site-packages (from requests>=2.9.1->locustio->locust) (1.25.8)
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in d:\softwares\python\python38-32\lib\site-packages (from gevent==1.5a3->locustio->locust) (0.4.15)
Requirement already satisfied: cffi>=1.12.2; platform_python_implementation == "CPython" and sys_platform == "win32" in d:\softwares\python\python38-32\lib\site-packages (from gevent==1.5a3->locustio->locust) (1.14.0)
Requirement already satisfied: six in d:\softwares\python\python38-32\lib\site-packages (from geventhttpclient-wheels==1.3.1.dev2->locustio->locust) (1.14.0)
Requirement already satisfied: MarkupSafe>=0.23 in d:\softwares\python\python38-32\lib\site-packages (from Jinja2>=2.10.1->flask>=0.10.1->locustio->locust) (1.1.1)
Requirement already satisfied: pycparser in d:\softwares\python\python38-32\lib\site-packages (from cffi>=1.12.2; platform_python_implementation == "CPython" and sys_platform == "win32"->gevent==1.5a3->locustio->locust) (2.20)
Installing collected packages: geventhttpclient-wheels, locustio, locust
    Running setup.py install for geventhttpclient-wheels ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\softwares\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sidha\\AppData\\Local\\Temp\\pip-install-l2qh2xpq\\geventhttpclient-wheels\\setup.py'"'"'; __file__='"'"'C:\\Users\\sidha\\AppData\\Local\\Temp\\pip-install-l2qh2xpq\\geventhttpclient-wheels\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sidha\AppData\Local\Temp\pip-record-s3e3z335\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\softwares\python\python38-32\Include\geventhttpclient-wheels'
         cwd: C:\Users\sidha\AppData\Local\Temp\pip-install-l2qh2xpq\geventhttpclient-wheels\
    Complete output (43 lines):
    d:\softwares\python\python38-32\lib\site-packages\setuptools\dist.py:471: UserWarning: Normalizing '1.3.1dev2' to '1.3.1.dev2'
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\client.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\connectionpool.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\header.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\httplib.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\response.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\url.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\useragent.py -> build\lib.win32-3.8\geventhttpclient
    copying src\geventhttpclient\__init__.py -> build\lib.win32-3.8\geventhttpclient
    running egg_info
    writing src\geventhttpclient_wheels.egg-info\PKG-INFO
    writing dependency_links to src\geventhttpclient_wheels.egg-info\dependency_links.txt
    writing requirements to src\geventhttpclient_wheels.egg-info\requires.txt
    writing top-level names to src\geventhttpclient_wheels.egg-info\top_level.txt
    reading manifest file 'src\geventhttpclient_wheels.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    writing manifest file 'src\geventhttpclient_wheels.egg-info\SOURCES.txt'
    creating build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\oncert.pem -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\server.crt -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\server.key -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_client.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_headers.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_httplib.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_keep_alive.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_network_failures.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_no_module_ssl.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_parser.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_ssl.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_url.py -> build\lib.win32-3.8\geventhttpclient\tests
    copying src\geventhttpclient\tests\test_useragent.py -> build\lib.win32-3.8\geventhttpclient\tests
    running build_ext
    building 'geventhttpclient._parser' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\softwares\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sidha\\AppData\\Local\\Temp\\pip-install-l2qh2xpq\\geventhttpclient-wheels\\setup.py'"'"'; __file__='"'"'C:\\Users\\sidha\\AppData\\Local\\Temp\\pip-install-l2qh2xpq\\geventhttpclient-wheels\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sidha\AppData\Local\Temp\pip-record-s3e3z335\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\softwares\python\python38-32\Include\geventhttpclient-wheels' Check the logs for full command output.
PS D:\Docker Sample Projects\cmder> locust
locust : The term 'locust' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ locust
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (locust:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\Docker Sample Projects\cmder> locust --version
locust : The term 'locust' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ locust --version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (locust:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
![locust_error](https://user-images.githubusercontent.com/33153967/78460828-d0bd2f80-76e1-11ea-8457-b3bf456e983b.JPG)
