### ISSUE TITLE
cookies with locust

### ISSUE THREAD

**Issue by vorticalbox** [gwik/geventhttpclient#118]
I am creating a locust to stress test some production servers and need access to cookies.

when using the default HTTP requests I can simply

```
self.client.get('/', cookies=cookies)
```
with cookies being a JSON object how do you achieve this using this package?

locust doc for reference
https://docs.locust.io/en/stable/increase-performance.html#increase-performance

**Comment by heyman** [comment]
This is probably more related to Locust than geventhttpclient. You can access the cookies using:

```python
self.client.cookiejar
```
