### ISSUE TITLE
Install locust failed due to geventhttpclient

### ISSUE THREAD

**Issue by wyatt-z** [gwik/geventhttpclient#131]
Install locust on Windows10-64bit with python3.8 and Microsoft Visual C++ 14.0, this is the message:
![Snipaste_2020-07-15_09-55-55](https://user-images.githubusercontent.com/6083180/87494549-e5ff0e00-c681-11ea-9b33-47d97d442b39.png)

Installing collected packages: geventhttpclient
    Running setup.py install for geventhttpclient ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hooply\\AppData\\Local\\Temp\\pip-install-y9_y11l_\\geventhttpclient\\setup.py'"'"'; __file__='"'"'C:\\Users\\hooply\\AppData\\Local\\Temp\\pip-install-y9_y11l_\\geventhttpclient\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hooply\AppData\Local\Temp\pip-record-ajhtzswu\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python38\Include\geventhttpclient'
         cwd: C:\Users\hooply\AppData\Local\Temp\pip-install-y9_y11l_\geventhttpclient\
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\geventhttpclient
    copying src\geventhttpclient\client.py -> build\lib.win-amd64-3.8\geventhttpclient
    copying src\geventhttpclient\connectionpool.py -> build\lib.win-amd64-3.8\geventhttpclient
    copying src\geventhttpclient\url.py -> build\lib.win-amd64-3.8\geventhttpclient
    copying src\geventhttpclient\useragent.py -> build\lib.win-amd64-3.8\geventhttpclient
    copying src\geventhttpclient\__init__.py -> build\lib.win-amd64-3.8\geventhttpclient
    running egg_info
    writing src\geventhttpclient.egg-info\PKG-INFO
    writing dependency_links to src\geventhttpclient.egg-info\dependency_links.txt
    writing requirements to src\geventhttpclient.egg-info\requires.txt
    writing top-level names to src\geventhttpclient.egg-info\top_level.txt
    reading manifest file 'src\geventhttpclient.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    warning: no files found matching 'CHANGELOG'
    writing manifest file 'src\geventhttpclient.egg-info\SOURCES.txt'
    running build_ext
    building 'geventhttpclient._parser' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

**Comment by cyberw** [comment]
Hi! You need Microsoft Visual C++ Build Tools, not  Microsoft Visual C++ Redistributable.

**Comment by heyman** [comment]
For some reason there's no Windows wheel file uploaded for the latests PyPI release, even though the 1.4.2 has one. It would be nice to get the Appveyor build to work (IIRC there was some problem with it?).

@wyatt-z One work-around could be to install the 1.4.2 version of geventhttpclient (`pip3 install geventhttpclient==1.4.2`)

**Comment by wyatt-z** [comment]
@heyman I tried to install geventhttpclient-1.4.2 first, and then install locust. It would uninstall geventhttpclient-1.4.2, and get the same problem. The Microsoft Visual C++ Build Tools solution may work, but it's not a good one, it seams have to install lots things.

**Comment by cyberw** [comment]
Sorry, should be fixed now.

Github -> appveyor config for geventhttpclient is broken somehow so I need to manually trigger appveyor to build the windows wheels.

**Comment by heyman** [comment]
@cyberw Nice!

@wyatt-z Ah, I see. I think it might still be possible using the `--no-deps` flag when pip installing locust. But since @cyberw has fixed the Windows wheels, that shouldn't be needed any more.
