### ISSUE TITLE
Problem with JSON in post request.

### ISSUE THREAD

**Issue by talaing** [gwik/geventhttpclient#133]
How to send JSON data in post request?
In other libraries like "requests" you can just add "json={}" but this client doesn't recognize it. Is there any way to send JSON data?

**Comment by cyberw** [comment]
You can do 
`data=json.dumps({...})`
you probably also need to set `headers={"content-type": "application/json", 'accept' = "application/json"}`

**Comment by talaing** [comment]
> You can do
> `data=json.dumps({...})`
> you probably also need to set
> `headers={"content-type": "application/json", 'accept' = "application/json"}`

Thanks for your answer, I fixed it but with one single change - I replaced `data` with `body`, so the full JSon looked like this
`body=json.dumps({...})`
Thanks :)
