### ISSUE TITLE
Add keep_blank_values and strict_parsing support for URL class

### ISSUE THREAD

**Issue by lostdragon** [gwik/geventhttpclient#51]
Use geventhttpclient.url.URL class to parse url, blank query string has missing in request, keep_blank_values and strict_parsing are urlparse.parse_qs default params, please add support keep_blank_values and strict_parsing pass to urlparse.parse_qs function.

**Comment by Apteryks** [comment]
Hello! Is it me, or this issue was closed without a proper resolution?
