### ISSUE TITLE
Should not hard-code use of SSLv3 in SSLConnectionPool

### ISSUE THREAD

**Issue by pjrobertson** [gwik/geventhttpclient#55]
With the recent [POODLE vulnerability](https://www.digitalocean.com/community/tutorials/how-to-protect-your-server-against-the-poodle-sslv3-vulnerability) in SSLv3 you probably shouldn't be hard-coding the use of SSLv3 in `SSLConnectionPool.py`

Many servers are now disabling SSLv3, which makes geventhttpclient basically broken

**Comment by romanlv** [comment]
can you push it to pypi? it's a serious problem and it seems to be fixed on master branch

**Comment by gwik** [comment]
It was on hold for python 2.7.10 and gevent releases. A took a while after that, but should be fixed in 1.2.0.
