### ISSUE TITLE
Bad descriptors with master

### ISSUE THREAD

**Issue by thedrow** [gwik/geventhttpclient#58]
```
Traceback (most recent call last):
  File "***", line 285, in request
    return HTTPConnectionPool.request(self, method, url, fields, headers, **urlopen_kw)
  File "***/lib/python2.7/site-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "***/lib/python2.7/site-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "***/lib/python2.7/site-packages/urllib3/connectionpool.py", line 536, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "***/lib/python2.7/site-packages/urllib3/connectionpool.py", line 294, in _get_conn
    if conn and is_connection_dropped(conn):
  File "***/lib/python2.7/site-packages/urllib3/util.py", line 490, in is_connection_dropped
    return select([sock], [], [], 0.0)[0]
  File "***/lib/python2.7/site-packages/gevent/select.py", line 67, in select
    raise error(*ex.args)
error: (9, 'Bad file descriptor')
```

Care to provide an explanation for why this happens so I'll be able to provide a fix?

**Comment by thedrow** [comment]
@gwik Did you try to reproduce it?

**Comment by ml31415** [comment]
Are you using geventhttpclient at all? It looks to me like you're using urllib3 with gevent monkey patched sockets. In that case, this bug report should better be placed here: https://github.com/shazow/urllib3

**Comment by thedrow** [comment]
@ml31415 The bug only occurs when I activate geventhttpclient with the following code:
```python
import geventhttpclient.httplib
geventhttpclient.httplib.patch()
```

Try it with any request. It will break.

**Comment by ml31415** [comment]
```python
import geventhttpclient.httplib
geventhttpclient.httplib.patch()
import urllib3
http = urllib3.PoolManager()
r = http.request('GET', 'http://heise.de')
print r.data
```

Works as intended for me. Tried it several times, didn't crash so far.

**Comment by thedrow** [comment]
I'll try to narrow it down to a reproducible test case.

**Comment by ml31415** [comment]
This it, what urllib3 ( https://github.com/shazow/urllib3/blob/master/urllib3/util/connection.py#L32 ) does, in order to check if the socket is still alive:
```python
        try:
            return select([sock], [], [], 0.0)[0]
        except socket.error:
            return True
```
This except statement doesn't handle errors thrown by gevent correctly, when the socket is already closed. gevent.select.select throws gevent.select.error (the thing, that you just got), not socket.error. So it's not caught here. But as they claim gevent compatibility, they should probably accept a bugreport and a fix for it.

**Comment by thedrow** [comment]
Issue https://github.com/shazow/urllib3/issues/541 filed upstream.
Thanks.
