### ISSUE TITLE
SSL fetching of https://antavo.com/ failed due to bad certificate

### ISSUE THREAD

**Issue by ghost** [gwik/geventhttpclient#64]
Chrome is dealing with this without any problem.
SSLConnectionPool:after_connect is failing on match_hostname
It seems that sock.getpeercert() returns different certificates than the ones I see when looking in Chrome

**Comment by pipermerriam** [comment]
I'm getting the same issue elsewhere.  My understanding is that the socket being used by `geventhttpclient` may need to be wrapped using `wrap_socket` or something similar to ensure that the hostname matching is happening in the correct context (which it currently is not) 

https://docs.python.org/3/library/ssl.html#ssl.SSLContext.wrap_socket

**Comment by ml31415** [comment]
Seems to work now with recent master.
