### ISSUE TITLE
Python 2.7.10 using ssl.get_default_verify_paths() returns directory path rather than full path to cert file

### ISSUE THREAD

**Issue by rusenask** [gwik/geventhttpclient#70]
Hey, 
I am using Python 2.7.10.
The trouble I am having is related to this part:
https://github.com/gwik/geventhttpclient/blob/master/src/geventhttpclient/connectionpool.py#L4-L15

since 
```python
    _certs = get_default_verify_paths()
    _CA_CERTS = _certs.cafile or _certs.capath
```
returns a directory path (_certs.cafile returns None so it's getting value from _certs.capath) rather than full path to a file - it fails. Currently the only solution I see is to just use certify. Commenting that line where it assigns variable to _CA_CERTS it fall backs to:

```python
import certifi
    _CA_CERTS = certifi.where()
```

and everything seems to work fine then.

**Comment by sadimusi** [comment]
As a workaround you can specify your own certificate path as an option when creating a `HTTPClient` instance:

````python
HTTPClient.from_url(url, ssl_options={
    'ca_certs': certifi.where()
})
````

**Comment by rusenask** [comment]
cool, haven't thought of that, just forked a project and fixed it on my branch.

**Comment by yanivhadad** [comment]
My solution was to add: `or os.path.isdir(_CA_CERTS)` to the condition so it will look like this:

```if not _CA_CERTS or os.path.isdir(_CA_CERTS):
    import certifi
    _CA_CERTS = certifi.where()```

**Comment by ml31415** [comment]
You're cordially invited to send some PR!

**Comment by yanivhadad** [comment]
@ml31415 me?

**Comment by ml31415** [comment]
Well, it looked like both of you had some fix working.
