### ISSUE TITLE
Invalid syntax for raise with Python 3

### ISSUE THREAD

**Issue by sbraz** [gwik/geventhttpclient#76]
I noticed while compiling the package that [this](https://github.com/gwik/geventhttpclient/blob/d66b1d96092e2cc323a906370d2aa792f2345934/src/geventhttpclient/useragent.py#L318) isn't valid in Python 3 and raises a `SyntaxError`.
Maybe you want to use something like [six.reraise](https://pythonhosted.org/six/#six.reraise) for portability?

**Comment by sbraz** [comment]
Do you think it will take a while before this is merged into the main branch and a new release is added to PyPI? Just so I know whether to patch it on Gentoo or wait for the new release.

**Comment by rmohr** [comment]
Seems like the whole useragent needs some more love for python3: https://github.com/gwik/geventhttpclient/pull/77. Still work in progress.

I don't know when I find the time to properly test it. @sbraz happy for any feedback  the patches in https://github.com/gwik/geventhttpclient/pull/77.
