### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by beerscorp** [gwik/geventhttpclient#83]
from geventhttpclient import HTTPClient
from geventhttpclient.url import URL

baseUrl = URL("http://www.abfall.mobi")
http = HTTPClient(host=baseUrl.host)
res = http.get('')

always segmentation fault.... 

====
(.venv)MacBook-Pro:sc Dave$ python3
Python 3.6.0 (default, Dec 24 2016, 08:02:28) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from geventhttpclient import HTTPClient
>>> from geventhttpclient.url import URL
>>> 
>>> 
>>> baseUrl = URL("http://www.abfall.mobi")
>>> http = HTTPClient(host=baseUrl.host)
>>> res = http.get('')
Segmentation fault: 11

**Comment by beerscorp** [comment]
curl -v http://www.abfall.mobi
* Rebuilt URL to: http://www.abfall.mobi/
* Hostname was NOT found in DNS cache
*   Trying 95.130.17.36...
* Connected to www.abfall.mobi (95.130.17.36) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: www.abfall.mobi
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 18 Jan 2017 04:24:08 GMT
* Server Apache is not blacklisted
< Server: Apache
< X-Powered-By: PHP/5.3.2-1ubuntu4.28
< Location: http://www.abf?lle.de
< Vary: Accept-Encoding
< Content-Length: 0
< Content-Type: text/html
< 
* Connection #0 to host www.abfall.mobi left intact

I feel like this is an issue
Location: http://www.abf?lle.de

but it doesn't help much ... as I'm not in control over server response

**Comment by 005** [comment]
just to add some details:
here is tail of strace when it fails "Location: http://www.abf\344lle.de\r\n"

epoll_wait(4, {{EPOLLIN, {u32=6, u64=8589934598}}}, 64, 4999) = 1
clock_gettime(CLOCK_MONOTONIC, {7744, 141815403}) = 0
recvfrom(6, "HTTP/1.1 301 Moved Permanently\r\nDate: Wed, 18 Jan 2017 12:54:23 GMT\r\nServer: Apache\r\nX-Powered-By: PHP/5.3.2-1ubuntu4.28\r\nLocation: http://www.abf\344lle.de\r\nVary: Accept-Encoding\r\nContent-Length: 0\r\nContent-Type: text/html\r\n\r\n", 4096, 0, NULL, NULL) = 224
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---

**Comment by beerscorp** [comment]
no issue when run on python 2.7  - so python 3 only

**Comment by ml31415** [comment]
Can't reproduce this unfortunately. Looks like the forward to `abfälle.de` is gone. Requestiong `abfälle.de` directly seems to work fine.
