### ISSUE TITLE
Add prebuilt wheels to PyPI

### ISSUE THREAD

**Issue by heyman** [gwik/geventhttpclient#93]
Would you consider uploading prebuilt python wheels to PyPI (for Linux, macOS & Windows)?

I have a branch in my fork where I've managed to get [Appveyor](https://www.appveyor.com/) to automatically build windows wheels for geventhttpclient with the use of [cibuildwheels](https://github.com/joerick/cibuildwheel). It was actually pretty easy to set up: https://github.com/heyman/geventhttpclient/commit/5d21a29bede8c299243cb5b59d18e3ab7f1ad831

Here's the Appveyor build: https://ci.appveyor.com/project/heyman/geventhttpclient

I can improve on that branch and get it to also build wheels for Linux and macOS on Travis.ci. The only thing you would need to do is then to download the prebuilt wheels and upload them to PyPI when making a new release. Would you be interested in such pull-request?

The reason I'm interested in this is because I'm working on a new HTTP client for [Locust](https://locust.io) that'll use geventhttpclient, and we don't want to add a dependency on having a build environment set up for people who want to install Locust: https://github.com/locustio/locust/pull/713

Edit:
It's also possible to set up Travis.ci and Appveyor to automatically upload the built wheel files when a new git tag is pushed. If one is willing to trust Travis & Appveyor with ones PyPI credentials, or at least credentials to an account that has upload access to the PyPI repo.

**Comment by heyman** [comment]
You would also have to sign up for Appveyor (free for open source projects) and activate it for the geventhttpclient repository.

**Comment by heyman** [comment]
I've now managed to get my fork to build both Linux, OSX and Windows wheels, as well as upload them to PyPI (to a separate geventhttpclient-wheels package: https://pypi.python.org/pypi/geventhttpclient-wheels), when a git tag is pushed.

Do you want me to make a pull-request with this? You would then have to sign up to Appveyor, turn on builds for this repository, and also configure PyPI credentials (for some account that has upload access to PyPI) on both Travis.ci and Appveyor.

Here you can see the diff of my branch:
https://github.com/gwik/geventhttpclient/compare/heyman:build-wheels-test-pypi

**Comment by heyman** [comment]
In order to save a communication round-trip, I went ahead and made a PR, but feel free to just close it if this is not something you're interested in :). In that case we'll probably resort to maintain our own separate geventhttpclient PyPI package with wheels, that Locust can depend on.

**Comment by ml31415** [comment]
As you probably noted already, there is currently not much development and maintenance going on with this project. If you're planning to use it for some commercial project, I'm afraid you'll have to be ready to do some of the maintainance for geventhttpclient on your own. All your proposals so far seem reasonable. Maybe @gwik can also give you commit rights for this?

**Comment by heyman** [comment]
@ml31415 Locust is an open-source project, though it's used by many companies commercially. I've used geventhttpclient successfully with Locust for a large project in the past, and I'm now working on an "official" client that shold be built into Locust (the default one is based in python requests which is really nice, but we get a 5x-6x performance increase by using geventhttpclient). .

If you think the proposal is good, and @gwik would give me commit access, I could definitely set up the building/uploading of binary wheels. Though I would need upload access to PyPI as well, to be able to set up the uploading (my PyPI username is "heyman").

We could also set up our own separate PyPI package that Locust can use, but I think it would benefit more people if the official package contained wheels!

**Comment by ml31415** [comment]
Hm, I hope @gwik will show up at some point. I could commit #94 , but I also don't have access to pypi. Besides that, open source or not, that won't help in that case unfortunately.

You had asked for a drop-in solution for request somewhere. A PR adding such a requests-like API for geventhttpclient would surely be welcome. I had implemented an adapter for integrating geventhttpclient into requests, but all the layers over layer in requests kill much of the performance. Better to add a thin API wrapper over the UserAgent to mimic requests. Shouldn't be hard to implement.

**Comment by heyman** [comment]
@ml31415 Yep, that's basically what I'm doing now (created a thin wrapper around UserAgent so that it mimics the basics of the requests API).

Yes, it's probably better to wait with merging #94, since it needs the PyPI upload to really be useful.

**Comment by heyman** [comment]
Any updates on this?

I'm planning to go ahead and set up a fork/mirror of this package on PyPI with prebuilt wheels, but I just wanted to check in here one more time, since I think it could benefit more people if the official package contained wheels.

**Comment by ml31415** [comment]
I'd be fine committing it, but without @gwik there is no way to get it to pypi.

**Comment by ml31415** [comment]
Should be fixed I guess.
