### ISSUE TITLE
Exists one error in code file useragent.py

### ISSUE THREAD

**Issue by jotagesales** [gwik/geventhttpclient#98]
![captura de tela 2018-08-05 as 19 27 57](https://user-images.githubusercontent.com/4000641/43690742-d619f462-98e5-11e8-97fa-c1aec9cbda92.png)

**Comment by ml31415** [comment]
Looks like the redirection in https://github.com/gwik/geventhttpclient/blob/master/src/geventhttpclient/useragent.py#L378 never sets `e` correctly.
